### PR TITLE
Propose slides for IETF 115

### PR DESCRIPTION
**Pull request by bemasc**

### CODE REVIEW

**Comment by richsalz** [comment]
I think "Update Overview" should be Update maybe.  But looks good!

**Comment by bemasc** [comment]
Hmm.  How about "Changes since IETF 114"?

**Comment by richsalz** [comment]
> Hmm. How about "Changes since IETF 114"?

Doh.  of course.

**Comment by bemasc** [comment]
Done

**Comment by sftcd** [comment]
only have one real coment/question: given this extends the draft-00 design, maybe we should also include the picture  from the ietf-114 pressie to make it clear that can still work? (And in case of confusion amongst WG participants.) So maybe add that before the current picture with a title like "draft-00 picture" then change title of current picture to "draft-01 also allows..." or something like that? (I can do edits to show what I mean if that's needed)

**Comment by bemasc** [comment]
I'm not sure I understand precisely what you're looking for, but I've expanded the diagram to describe how the origin reads its configuration from the front origin, if it is not generating its own ECHConfig.  Does this address your concern?

**Comment by sftcd** [comment]
I made a couple of tweaks but figure this is fine now so will merge and propose as slides for TLS session. We can fix during the week if needed.

**Pull request merged**
